import React from "react";

const interventions = [
  {
    title: "Precision Nutritional Shields",
    desc: "Eliminating specific offending nutrients from the infant's diet while providing the exact amino acids or energy substitutes their engine requires.",
  },
  {
    title: "Enzymatic & Co-Factor Support",
    desc: "Supplying high-dose vitamin co-factors (such as B-vitamins or Carnitine) to stimulate sluggish alternate pathways and bypass the genetic bottleneck.",
  },
  {
    title: "Proactive Emergency Protocols",
    desc: "Giving families and paediatricians clear guidelines to manage routine childhood illnesses safely, avoiding metabolic stress before it starts.",
  },
];

const NewbornScreeningIntervention = () => {
  return (
    <section className="w-full py-10 md:py-14 bg-gray-50 font-roboto">
      <div className="max-w-5xl mx-auto px-4 text-left">
        <h2 className="text-2xl md:text-[28px] font-bold text-gray-800 mb-4">
          Knowledge is Power. Early Intervention is the Cure.
        </h2>

        <p className="text-gray-600 text-base md:text-lg leading-relaxed mb-4 max-w-3xl">
          The most vital takeaway for parents and healthcare providers is that an abnormal metabolic score is a call to immediate action, not a final sentence. Inborn Errors of Metabolism cannot be altered genetically, but their physical and neurological outcomes can be entirely controlled.
        </p>

        <p className="text-gray-600 text-base md:text-lg leading-relaxed mb-10 max-w-3xl">
          Based on the highly precise data map generated by this panel, clinical teams can instantly deploy targeted, personalized strategies:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {interventions.map((item, idx) => (
            <div
              key={idx}
              className="bg-white rounded-xl p-6 shadow-[0_0_10px_#e5e5e5] hover:shadow-[0_4px_20px_rgba(0,0,0,0.1)] transition-all duration-300 text-left"
            >
              <div
                className="w-12 h-12 rounded-lg flex items-center justify-center mb-4 text-white font-bold text-lg"
                style={{ background: "linear-gradient(to right, #15AEE5, #0C607F)" }}
              >
                {idx + 1}
              </div>
              <h3 className="text-lg font-semibold text-[#005C96] mb-2">
                {item.title}
              </h3>
              <p className="text-gray-600 text-base leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default NewbornScreeningIntervention;
