import React from "react";

const interventions = [
  {
    title: "Precision Dose Recalibration",
    desc: "Increasing subsequent doses to achieve a true therapeutic baseline and gain control over symptoms, or lowering them to clear away unwanted side effects and toxic organ strain.",
  },
  {
    title: "Drug Interaction Mapping",
    desc: "Identifying if your anti-epileptic drug is inadvertently speeding up or slowing down the clearance of your neuroleptic, allowing for safe, simultaneous adjustments.",
  },
  {
    title: "Guaranteed Long-Term Safety",
    desc: "Securing the exact data required to maintain your medication at the lowest effective dose, protecting your brain health, metabolic baseline, and cognitive clarity over a lifetime.",
  },
];

const NeuropsychIntervention = () => (
  <section className="w-full py-8 sm:py-10 md:py-14 bg-gray-50 font-roboto">
    <div className="max-w-5xl mx-auto px-4 sm:px-6 text-center sm:text-left">
      <h2 className="text-xl sm:text-2xl md:text-[28px] font-bold text-gray-800 mb-3 sm:mb-4">
        Knowledge is Power. Real-Time Intervention is the Cure.
      </h2>
      <p className="text-gray-600 text-sm sm:text-base md:text-lg leading-relaxed mb-3 sm:mb-4 max-w-3xl mx-auto sm:mx-0">
        The most vital takeaway from your neuropsychiatric TDM assessment is that your dosing profile is entirely dynamic. Because this panel captures an active, real-time snapshot of your drug metabolism, your dosages can be systematically shifted, customized, and optimized to fit your body's exact clearance engine. An abnormal initial level is not a setback; it is an immediate call to action that allows your medical team to safely optimize your treatment before complications develop.
      </p>
      <p className="text-gray-600 text-sm sm:text-base md:text-lg leading-relaxed mb-6 sm:mb-10 max-w-3xl mx-auto sm:mx-0">
        Based on the precise data map generated by this panel, your clinical team can instantly customize your recovery strategy:
      </p>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6">
        {interventions.map((item, idx) => (
          <div
            key={idx}
            className="metab-card bg-white rounded-xl p-4 sm:p-6 shadow-[0_0_10px_#e5e5e5] hover:shadow-[0_4px_20px_rgba(0,0,0,0.1)] transition-all duration-300 text-left h-full"
          >
            <div
              className="w-10 h-10 sm:w-12 sm:h-12 rounded-lg flex items-center justify-center mb-3 sm:mb-4 text-white font-bold text-base sm:text-lg"
              style={{ background: "linear-gradient(to right, #15AEE5, #0C607F)" }}
            >
              {idx + 1}
            </div>
            <h3 className="text-base sm:text-lg font-semibold text-[#005C96] mb-2 leading-snug">{item.title}</h3>
            <p className="text-gray-600 text-sm sm:text-base leading-relaxed">{item.desc}</p>
          </div>
        ))}
      </div>
    </div>
  </section>
);

export default NeuropsychIntervention;
