import React from "react";

const interventions = [
  {
    title: "Precision Rescue Calibration",
    desc: "Dynamically scaling up your hydration, urinary alkalinization, or Leucovorin rescue doses to neutralize excess drug levels and completely prevent toxic side effects.",
  },
  {
    title: "Organ Protection Sequencing",
    desc: "Activating proactive shields to protect your kidneys, liver, and mucosal linings the moment a slower-than-average clearance rate is detected.",
  },
  {
    title: "Optimized Protocol Timing",
    desc: "Safely mapping out the exact, secure window for your next scheduled treatment cycle based on verified, molecular proof of full drug clearance.",
  },
];

const MethotrexateIntervention = () => (
  <section className="w-full py-10 md:py-14 bg-gray-50 font-roboto">
    <div className="max-w-5xl mx-auto px-4 text-left">
      <h2 className="text-2xl md:text-[28px] font-bold text-gray-800 mb-4">
        Knowledge is Power. Real-Time Intervention is the Cure.
      </h2>
      <p className="text-gray-600 text-base md:text-lg leading-relaxed mb-4 max-w-3xl">
        The most vital takeaway from your Methotrexate TDM assessment is that your clearance profile is entirely dynamic. Because this panel captures an active, real-time snapshot of drug metabolism, your treatment protocol can be systematically shifted, customized, and optimized to fit your body's exact renal clearance speed. An elevated or delayed clearance marker is not a setback; it is an immediate call to action that allows your medical team to safely adjust your care.
      </p>
      <p className="text-gray-600 text-base md:text-lg leading-relaxed mb-10 max-w-3xl">
        Based on the precise data map generated by this panel, your clinical team can instantly deploy targeted, personalized strategies:
      </p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {interventions.map((item, idx) => (
          <div
            key={idx}
            className="bg-white rounded-xl p-6 shadow-[0_0_10px_#e5e5e5] hover:shadow-[0_4px_20px_rgba(0,0,0,0.1)] transition-all duration-300 text-left"
          >
            <div
              className="w-12 h-12 rounded-lg flex items-center justify-center mb-4 text-white font-bold text-lg"
              style={{ background: "linear-gradient(to right, #15AEE5, #0C607F)" }}
            >
              {idx + 1}
            </div>
            <h3 className="text-lg font-semibold text-[#005C96] mb-2">{item.title}</h3>
            <p className="text-gray-600 text-base leading-relaxed">{item.desc}</p>
          </div>
        ))}
      </div>
    </div>
  </section>
);

export default MethotrexateIntervention;
