export const ngsPanelTests = [
  { name: "Whole Exome Sequencing - Clinical Report" },
  { name: "Cardiomyopathy gene panel" },
  { name: "Arrhythmias and Channelopathies" },
  { name: "Sudden Cardiac Death" },
  { name: "Aortic Vascular Diseases (Aortopathy)" },
  { name: "Hypercholesterolemia and Dyslipidemia" },
  { name: "Congenital and other Inherited Cardio Vascular Diseases" },
  { name: "ATRX gene analysis" },
  { name: "Brown Vialetto–Van Laere syndrome gene panel" },
  { name: "Familial hemiplegic migraine gene panel" },
  { name: "Lissencephaly gene panel" },
  { name: "MECP2 gene sequencing" },
  { name: "Microcephaly gene panel" },
  { name: "Neuronal migration disorder gene panel" },
  { name: "Pontocerebellar hypoplasia gene panel" },
  { name: "Rett Syndrome gene panel" },
  { name: "Aicardi-Goutieres syndrome gene panel" },
  { name: "Benign infantile epilepsy gene panel" },
  { name: "Dravet syndrome (SCN1A) gene analysis" },
  { name: "Epileptic encephalopathy gene panel" },
  { name: "Familial female mental retardation/epilepsy gene panel" },
  { name: "Progressive myoclonic epilepsy gene panel" },
  { name: "TBC1D24 gene analysis" },
  { name: "Ataxia-telangiectasia (ATM) gene analysis" },
  { name: "Dystonia gene panel" },
  { name: "Early-onset juvenile parkinsonism gene panel" },
  { name: "Episodic ataxia gene panel" },
  { name: "Hereditary spastic paraplegia gene panel" },
  { name: "Hyperekplexia gene panel" },
  { name: "Neurotransmitter disorders gene panel" },
  { name: "Neurofibromatosis (NF1 and NF2) gene analysis" },
  { name: "Neurofibromatosis type 2 (NF2) gene analysis" },
  { name: "TSC1 & TSC2 gene analysis" },
  { name: "4H syndrome gene panel" },
  { name: "Adrenoleukodystrophy (ABCD1) gene analysis" },
  { name: "Alexander disease (GFAP) gene analysis" },
  { name: "Alkaptonuria (HGD) gene analysis" },
  { name: "Canavan disease (ASPA) gene analysis" },
  { name: "Cystic megalencephaly (MLC1) gene analysis" },
  { name: "Giant axonal neuropathy-1 (GAN) gene analysis" },
  { name: "Hypomyelination syndrome gene panel" },
  { name: "Joubert syndrome gene panel" },
  { name: "Krabbe disease (GALC) gene analysis" },
  { name: "Leukodystrophy gene panel" },
  { name: "Metachromatic leukodystrophy gene panel" },
  { name: "Neurodegeneration with brain iron accumulation gene panel" },
  { name: "Neuronal ceroid lipofuscinosis gene panel" },
  { name: "NOTCH3 (CADASIL) gene analysis" },
  { name: "Tay-Sachs disease (HEXA) gene analysis" },
  { name: "Arthrogryposis & congenital myasthenic syndrome gene panel" },
  { name: "Charcot-Marie-Tooth and sensory neuropathies gene panel" },
  { name: "Duchenne Muscular Dystrophy (DMD) gene sequencing" },
  {
    name: "Fukuyama Congenital Muscular Dystrophy (FKTN) gene sequencing (does not include repeat expansions)",
  },
  { name: "Muscular dystrophy & congenital myopathy gene panel" },
  { name: "Myotonia congenita gene panel" },
  {
    name: "PMP22 gene analysis (inflammatory demyelinating polyneuropathy screen)",
  },
  { name: "Spinal Muscular Atrophy gene Panel" },
  { name: "Neurology Genetic Disorder Test" },
  { name: "Bardet-Biedl syndrome gene panel" },
  { name: "Cantu syndrome (ABCC9) gene sequencing" },
  { name: "Ciliopathy gene panel" },
  { name: "Cockayne syndrome gene panel" },
  { name: "Cohen's syndrome (VPS13B) gene analysis" },
  { name: "Cornelia de Lange syndrome gene panel" },
  { name: "Craniosynostosis gene panel" },
  { name: "Cystic fibrosis (CFTR) gene analysis" },
  { name: "Fraser syndrome gene panel" },
  { name: "Johanson-Blizzard syndrome (UBR1) gene analysis" },
  { name: "Klippel-Feil syndrome gene panel" },
  { name: "Newborn screening gene panel" },
  { name: "Non-immune hydrops gene panel" },
  { name: "Noonan syndrome gene panel" },
  { name: "Pallister Hall syndrome (GLI3) gene analysis" },
  { name: "PDGFRB gene sequencing" },
  { name: "POLG gene sequencing" },
  { name: "Pulmonary alveolar microlithiasis (SLC34A2) gene analysis" },
  { name: "Pulmonary surfactant metabolism dysfunction gene panel" },
  { name: "Rasopathy gene panel" },
  { name: "Seckel syndrome gene panel" },
  { name: "Smith-Lemli-Opitz syndrome (DHCR7) gene analysis" },
  { name: "Sotos syndrome gene panel" },
  { name: "TTN gene sequencing" },
  { name: "Rare Inherited Genetic Disorder Test" },
  { name: "Alpha-mannosidosis (MAN2B1) gene analysis" },
  { name: "Biotinidase deficiency (BTD) gene analysis" },
  { name: "Citrullinemia gene panel" },
  { name: "Fabry disease (GLA) gene analysis" },
  { name: "Fanconi bickel syndrome (SLC2A2) gene analysis" },
  { name: "Farber lipogranulomatosis (ASAH1) gene analysis" },
  { name: "Fatty acid oxidation disorders gene panel" },
  { name: "Fucosidosis (FUCA1) gene analysis" },
  { name: "Galactosemia (GALT) gene analysis" },
  { name: "Galactosialidosis (CTSA) gene analysis" },
  { name: "Gaucher disease (GBA) gene analysis" },
  { name: "GLUT1 deficiency (SLC2A1) gene analysis" },
  { name: "Glycine encephalopathy gene panel" },
  { name: "Glycogen storage disorder gene panel" },
  { name: "Glycosylation (CDG) disorders gene panel" },
  {
    name: "GM1 gangliosidosis/mucopolysaccharidosis type IVB (GLB1) gene analysis",
  },
  { name: "Hereditary fructose intolerance (ALDOB) gene sequencing" },
  { name: "Homocystinuria gene panel" },
  { name: "Hyperargininemia (ARG1) gene analysis" },
  { name: "Leigh syndrome & mitochondrial encephalopathy gene panel" },
  { name: "Lysosomal acid lipase deficiency (LIPA) gene analysis" },
  { name: "Maple syrup urine disease gene panel" },
  { name: "McArdle disease (PYGM) gene analysis" },
  { name: "Menkes disease (ATP7A) gene analysis" },
  { name: "Methylmalonic aciduria gene panel" },
  { name: "Mucopolysaccharidosis gene panel" },
  { name: "Niemann-Pick disease gene panel" },
  { name: "Organic acidemia gene panel" },
  {
    name: "Peroxisomal disorder gene panel (includes adrenoleukodystrophy)",
  },
  { name: "Phenylketonuria (PAH) gene analysis" },
  { name: "Pompe disease (GAA) gene analysis" },
  { name: "Sialidosis (NEU1) gene analysis" },
  { name: "Urea cycle defects gene panel" },
  { name: "Metabolic Genetic Disorder Test" },
  { name: "C8orf37 gene sequencing" },
  { name: "Congenital cataract gene panel" },
  { name: "Congenital stationary night blindness gene panel" },
  { name: "Corneal dystrophy gene panel" },
  { name: "Leber congenital amaurosis gene panel" },
  { name: "Microphthalmia and anophthamia gene panel" },
  { name: "Optic atrophy gene panel" },
  { name: "Retinal degeneration gene panel" },
  { name: "Usher syndrome gene panel" },
  { name: "Ophthalmology Genetic Disorder Test" },
  { name: "Achondroplasia (FGFR3) gene analysis" },
  { name: "Hereditary multiple exostoses gene panel" },
  { name: "Osteogenesis imperfecta gene panel" },
  { name: "Osteopetrosis gene panel" },
  {
    name: "Pachydermoperiostosis & primary hypertrophic osteoarthropathy gene panel",
  },
  { name: "Skeletal Dysplasia Genetic Disorder Test" },
  { name: "Alport syndrome gene panel" },
  { name: "Bartter syndrome gene panel" },
  { name: "Meckel Gruber syndrome gene panel" },
  { name: "Nephrotic syndrome gene panel" },
  { name: "Polycystic kidney disease gene panel" },
  { name: "Primary hyperoxaluria gene panel" },
  { name: "Xanthinuria gene panel" },
  { name: "Nephrology Genetic Disorder Test" },
  { name: "Aplastic anemia gene panel" },
  { name: "Beta thalassemia [HBB] gene analysis" },
  { name: "Bone marrow failure syndrome gene panel" },
  {
    name: "Haemophilia A (F8) gene analysis (along with analysis of the F8-intron 22 inversion)",
  },
  { name: "Congenital afibrinogenemia gene panel" },
  { name: "Congenital amegakaryocytic thrombocytopenia (MPL) gene analysis" },
  { name: "Congenital dyserythropoietic anemia gene panel" },
  { name: "Diamond blackfan anemia gene panel" },
  { name: "Dyskeratosis congenita gene panel" },
  { name: "Factor VII deficiency (F7) gene analysis" },
  { name: "Fanconi anemia gene panel" },
  { name: "G6PD gene sequencing" },
  { name: "Haemophilia (F8 & F9) gene panel" },
  {
    name: "Haemophilia A (F8) gene analysis (analysis of the F8 inversion is not included)",
  },
  { name: "Haemophilia B (F9) gene analysis" },
  { name: "Hemophagocytic lymphohistiocytosis (HLH) gene panel" },
  { name: "Hereditary elliptocytosis gene panel" },
  {
    name: "Hereditary Hemolytic Anemia Panel (For RBC membrane disorders and Enzymopathies)",
  },
  { name: "Hereditary spherocytosis gene panel" },
  { name: "Iron-refractory iron deficiency anemia (TMPRSS6) gene analysis" },
  { name: "Methemoglobinemia (CYB5R3) gene analysis" },
  { name: "Sideroblastic anaemia gene panel" },
  { name: "Von Willebrand disease (VWF) gene analysis" },
  { name: "Wiskott Aldrich syndrome (WAS) gene analysis" },
  { name: "Hematology Genetic Disorder Test" },
  { name: "Agammaglobulinemia (BTK) gene analysis" },
  { name: "Chediak-Higashi syndrome (LYST) gene analysis" },
  { name: "Congenital neutropenia gene panel" },
  { name: "Hyper-immunoglobulin E syndrome (DOCK8) gene sequencing" },
  { name: "Primary immunodeficiency gene panel" },
  { name: "Severe combined immunodeficiency (SCID) gene panel" },
  { name: "Thrombotic Thrombocytopenic Purpura (ADAMTS13) gene analysis" },
  { name: "Immunology Genetic Disorder Test" },
  { name: "Alstrom syndrome (ALMS1) gene analysis" },
  { name: "Androgen receptor (AR) gene analysis" },
  {
    name: "Congenital adrenal hyperplasia CYP21A2 (21-0H) NGS and deletion/duplication analysis",
  },
  { name: "Congenital adrenal hyperplasia CYP21A2 (21-0H) gene analysis" },
  {
    name: "Congenital adrenal hyperplasia due to 3-beta-hydroxysteroid dehydrogenase 2 deficiency (HSD3B2) gene analysis",
  },
  { name: "Congenital hypopituitarism gene panel" },
  { name: "Hereditary pancreatitis gene panel" },
  { name: "Hypercholesterolemia gene panel" },
  { name: "Kallmann syndrome gene panel" },
  { name: "Leptin deficiency (LEP) gene analysis" },
  {
    name: "Maturity-onset diabetes of the young (MODY) & neonatal diabetes gene panel",
  },
  { name: "Monogenic and syndromic obesity gene panel" },
  { name: "Endocrinology Genetic Disorder Test" },
  { name: "Deafness gene panel" },
  { name: "Mondini defect (SLC26A4) gene analysis" },
  { name: "Waardenburg syndrome gene panel" },
  { name: "ENT Genetic Disorder Test" },
  { name: "Alagille syndrome gene panel" },
  { name: "Congenital hepatic fibrosis gene panel" },
  {
    name: "Gilbert syndrome (UGT1A1) gene analysis (only point mutation analysis)",
  },
  { name: "Hemochromatosis gene panel" },
  { name: "Polycystic liver disease gene panel" },
  { name: "Progressive familial intrahepatic cholestasis gene panel" },
  { name: "Tyrosinemia gene analysis" },
  { name: "Wilson disease (ATP7B) gene analysis" },
  { name: "Gastroenterology Genetic Disorder Test" },
  { name: "Cutis-laxa gene panel" },
  { name: "Ehler Danlos syndrome gene panel" },
  { name: "Marfan syndrome (FBN1) gene analysis" },
  { name: "Connective Tissue Genetic Disorder Test" },
  { name: "Ectodermal dysplasia gene panel" },
  { name: "Epidermolysis bullosa gene panel" },
  { name: "Harlequin ichthyosis (ABCA12) gene analysis" },
  { name: "Icthyosis gene panel" },
  { name: "Oculocutaneous albinism gene panel" },
  { name: "Sjogren-Larsson syndrome (ALDH3A2) gene analysis" },
  { name: "Xeroderma pigmentosum gene panel" },
  { name: "Acute intermittent porphyria - HMBS gene analysis" },
  { name: "Dermatology Genetic Disorder Test" },
];
